<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SQ1HPPK" failures="1" tests="4" name="regression test" time="0.191" errors="0" timestamp="2022-12-08T10:52:08 IST">
  <testcase classname="com.testng.examples.TestNGDemo" name="testCase1" time="0.007"/>
  <testcase classname="com.testng.examples.TestNGDemo" name="testCase2" time="0.006">
    <failure type="java.lang.AssertionError" message="Failed this testcase intentionally">
      <![CDATA[java.lang.AssertionError: Failed this testcase intentionally
at com.testng.examples.TestNGDemo.testCase2(TestNGDemo.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="com.testng.examples.TestNGDemo2" name="testCase3" time="0.002"/>
  <testcase classname="com.testng.examples.TestNGDemo2" name="testCase4" time="0.002"/>
</testsuite> <!-- regression test -->
